dist: xenial
language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
install:
  - pip install pip -U
  - pip install -r requirements-dev.txt
env:
  - NOTHREAD=true
script:
  - flake8 --ignore=E128,E501,E731 --statistics andriller/
  - pytest --cov=andriller tests/
deploy:
  provider: pypi
  user: denco
  password:
    secure: WK43G6u49vfxqeKvrs97MAjX2xeNKTNx5zn1Xv0LADPxQLsdmgOISSxJKQZqtExaoS32JwUuLZ5hVadbl4FEhN16bG4+iYEQlrmNzyASLJdfN2svX5Cxb36wzrQjJx1+kC5JTQLRzZxLFXlSaKVOqU+bJbvmkHlp/lIZ6nALUGYHQc72uYi4mQ7O11hxuUxbMV91YxiGxT/Em/Pe4n52lJesUlz7mfKsmCbmezIvWeGkTj5hjO91AZmdOT2jUjkmwWNjF4kbjqI2pSVFg8NinM4+Iet7M1vHk3c5awjEpKCFp8uwdgc6AB3KKcIQnXF9WfcNGpClKLlwDH+zesj2OSLRMtlS/uU8vV/txjjbcyCBsOyk+0fSguHAfUFsUrI/sm1lSUvrGL+/P6DdvFn9xjBNwvUI7e7iUrnGJ+bToKRXvD4QaoyQDOheIX6kyukVte37NC4msnR7YJRO8XSaUaISrT1pxceI1GEtpjOvxW0gHnB+Sjg6TtYrJ351xUzPEZ77Kx7r1tOCLCFBUH8rLk0gNIXGgofaVQO1RxIvrXvQUAuKIKzteEpx+MY7dWnAqWpdy2GHI9xVs7CG1HnWsvkTEBl05MhlivIaW2eHm1rsC41WAU1Ia/tksZyAxqxNcEXRZ5tUj/sKt6sjTuqxD6zHO4lS8AbMRwpZGA0Hg60=
  skip_existing: true
  distributions: bdist_wheel
  on:
    branch: master
    tags: true
